version: "3"
services:
    app:
        build:
            context: ../../
            dockerfile: ./ops-tools/docker/images/app/Dockerfile
        command: sh -c "mvn package && java -jar target/docker-practice-java-0.0.1-SNAPSHOT.jar"
        volumes:
            - ../../:/app
        ports:
            - "8080:8080"
            - "8888:8080"
        networks:
            - docker-practice-net
        depends_on:
            - redis
            - postgresql

    redis:
        image: redis:6.0.9-alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - docker-practice-net

    postgresql:
        image: postgres:14-alpine
        restart: unless-stopped
        ports:
            - "5432:5432"
        networks:
            - docker-practice-net
        volumes:
            - ../../data/postgres/:/var/lib/postgres/data
            - ../../data/dump/:/db/dump
        environment:
            - POSTGRES_PASSWORD=school
            - POSTGRES_USER=postgres
            - POSTGRES_DB=school

networks:
    docker-practice-net:
        driver: bridge
